# Setup
title:               'F[Abulous]'
tagline:             "Adam's Tech Blog"
description:         'A thought dumping ground.'
url:                 https://adamjking.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Adam King
  url: abc
  email:             adamjking1995@outlook.com

# Gems
plugins:
  - jekyll-paginate

version: 1